### ISSUE TITLE
kio.save_overlay() not working on mac

### ISSUE THREAD

**Issue by AnnoKoetje** [sjcross/ctraptools#3]
The kio.save_overlay() function does not seem to work on mac. I think the problem is the following line:
```
myFont = ImageFont.truetype("arial.ttf", 16)
```
According to google the code should be the following to work on mac:
```
myFont = ImageFont.truetype('/Library/Fonts/Arial.ttf', 16)
```
I have tested the mac specific code and this fixes the issues for me. I don't know if this will be easy to fix so it works for both mac and windows

**Comment by sjcross** [comment]
Good spot!  I've dug a bit deeper into this and apparently Pillow (the text renderer) only indexes fonts on Windows.

To keep this as platform agnostic as possible, I've now created a new release where the fonts (should!) be packaged with the code.  When using this, Python will hopefully load the fonts from this folder rather than having to find them in the operating system's own fonts folder.

To get this latest version you should just need re-run the following command and it'll hopefully find version 0.2.0
```
pip install git+https://github.com/sjcross/ctraptools
```

Please could you let me know if this works on your computer.

**Comment by AnnoKoetje** [comment]
Thanks for looking into this! I have installed version 0.2.0 but am still getting the same error. It now identifies the changed line as being the problem

```
myFont = ImageFont.truetype(pkg_resources.resource_filename('ctraptools','resources/fonts/Roboto-Regular.ttf'), 16)
```

The error message is the same "OSError: cannot open resource"

**Comment by sjcross** [comment]
I think the resources declaration may not have been quite right.  Would you mind running the install command once again and seeing if it can then access the fonts.  At least when I tested this on windows it went from not working to now working.

**Comment by AnnoKoetje** [comment]
I have just run the install again and got the same error when trying  ```kio.save_overlay()```

I am not 100% sure the install definitely changed to the new version as the version number is the same so I couldn't check if its definitely the new version

**Comment by AnnoKoetje** [comment]
I installed version 0.2.1 and it works now. Thanks for fixing this!
